version: '3.1'

services:

  app:
    build:
      context: .
    container_name: quizapp
    depends_on:
      - db
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/quizdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=
    ports:
      - "8080:8080"

  db:
    container_name: pg_quiz_container
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    environment:
      TZ: "America/Sao_Paulo"
      POSTGRES_DB: quizdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"

volumes:
  db-data: