spring:
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#
  jpa:
    generate-ddl: 'false'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'

  datasource:
    password:
    username: postgres
    url: jdbc:postgresql://localhost:5432/quizdb